library(stringr)
library(readr)
suppressPackageStartupMessages(library("dplyr"))

data1 <- read.csv("/Users/lina/Documents/CPEN442/unlocking/Data/out-afaa80bdc9bc347754db7213056c0e00ba011e13.csv", sep=",", header=FALSE)
data1$Date1 <- str_extract(data1$Date1,"[0-9]{4}-[0-9]{2}-[0-9]{2}")
data1$Date1 <- as.factor(data1$Date1)
data1$Date2 <- str_extract(data1$Date2,"[0-9]{4}-[0-9]{2}-[0-9]{2}")
data1$Date2 <- as.factor(data1$Date2)
data1$Date3 <- str_extract(data1$Date3,"[0-9]{4}-[0-9]{2}-[0-9]{2}")
data1$Date3 <- as.factor(data1$Data3)
write_csv(data1,"/Users/lina/Documents/CPEN442/unlocking/Data/linaOut1.csv")

data2 <- read.csv("/Users/lina/Documents/CPEN442/unlocking/Data/out2.csv")
data2$Date1 <- str_extract(data1$Date1,"[0-9]{4}-[0-9]{2}-[0-9]{2}")
data2$Date1 <- as.factor(data1$Date1)
data2$Date2 <- str_extract(data1$Date2,"[0-9]{4}-[0-9]{2}-[0-9]{2}")
data2$Date2 <- as.factor(data1$Date2)
data2$Date3 <- str_extract(data1$Date3,"[0-9]{4}-[0-9]{2}-[0-9]{2}")
data2$Date3 <- as.factor(data1$Data3)
write_csv(data2,"/Users/lina/Documents/CPEN442/unlocking/Data/linaOut2.csv")

data3 <- read.csv("/Users/lina/Documents/CPEN442/unlocking/Data/out3.csv")
data3$Date1 <- str_extract(data3$Date1,"[0-9]{4}-[0-9]{2}-[0-9]{2}")
data3$Date1 <- as.factor(data3$Date1)
data3$Date2 <- str_extract(data3$Date2,"[0-9]{4}-[0-9]{2}-[0-9]{2}")
data3$Date2 <- as.factor(data3$Date2)
data3$Date3 <- str_extract(data3$Date3,"[0-9]{4}-[0-9]{2}-[0-9]{2}")
data3$Date3 <- as.factor(data3$Data3)
write_csv(data1,"/Users/lina/Documents/CPEN442/unlocking/Data/linaOut3.csv")

data4 <- read.csv("/Users/lina/Documents/CPEN442/unlocking/Data/out4.csv")
data4$Date1 <- str_extract(data4$Date1,"[0-9]{4}-[0-9]{2}-[0-9]{2}")
data4$Date1 <- as.factor(data4$Date1)
data4$Date2 <- str_extract(data4$Date2,"[0-9]{4}-[0-9]{2}-[0-9]{2}")
data4$Date2 <- as.factor(data4$Date2)
data4$Date3 <- str_extract(data4$Date3,"[0-9]{4}-[0-9]{2}-[0-9]{2}")
data4$Date3 <- as.factor(data4$Data3)
write_csv(data4,"/Users/lina/Documents/CPEN442/unlocking/Data/linaOut4.csv")

data5 <- read.csv("/Users/lina/Documents/CPEN442/unlocking/Data/out5.csv")
data5$Date1 <- str_extract(data5$Date1,"[0-9]{4}-[0-9]{2}-[0-9]{2}")
data5$Date1 <- as.factor(data5$Date1)
data5$Date2 <- str_extract(data5$Date2,"[0-9]{4}-[0-9]{2}-[0-9]{2}")
data5$Date2 <- as.factor(data5$Date2)
data5$Date3 <- str_extract(data5$Date3,"[0-9]{4}-[0-9]{2}-[0-9]{2}")
data5$Date3 <- as.factor(data5$Data3)
write_csv(data5,"/Users/lina/Documents/CPEN442/unlocking/Data/linaOut5.csv")

data6 <- read.csv("/Users/lina/Documents/CPEN442/unlocking/Data/out6.csv")
data6$Date1 <- str_extract(data6$Date1,"[0-9]{4}-[0-9]{2}-[0-9]{2}")
data6$Date1 <- as.factor(data6$Date1)
data6$Date2 <- str_extract(data6$Date2,"[0-9]{4}-[0-9]{2}-[0-9]{2}")
data6$Date2 <- as.factor(data6$Date2)
data6$Date3 <- str_extract(data6$Date3,"[0-9]{4}-[0-9]{2}-[0-9]{2}")
data6$Date3 <- as.factor(data6$Data3)
write_csv(data6,"/Users/lina/Documents/CPEN442/unlocking/Data/linaOut6.csv")

allData <- rbind(data1,data2,make.row.names=TRUE)
allData <- rbind(allData,data3,make.row.names=TRUE)
allData <- rbind(allData,data4,make.row.names=TRUE)
allData <- rbind(allData,data5,make.row.names=TRUE)
allData <- rbind(allData,data6,make.row.names=TRUE)

allLSESData <- allData %>% filter(sesType=="LSES")
LSES <- allLSESData %>% group_by(Date1) %>% summarise(locked=n())
allUSESData <- allData %>% filter(sesType=="USES")
USES <- allUSESData %>% group_by(Date1) %>% summarise(unlocked=n())
OverallData <- allData %>% filter(sesType %in% c("LSES","USES"))
Overall <- OverallData %>% group_by(Date1) %>% summarise(Overall=n())

mergeData <- merge(Overall,allLSESData,by="Date1")
mergeData <- merge(mergeData,allUSESData,by="Date1")
interactionsDat <- mergeData %>% select(Overall,locked,unlocked)
boxplot(interactionsDat,ylab="Average nr of interactions per day")


################################### USELESS
#Get the corresponding columns we care about out from the total dataset
total <- total %>% select(V1,V2,V3,V4,V7)
#Set proper column names to these 7 columns
colnames(total) <- c("userID","sesType","sesPart1Len","sesPart2Len","date")
total$date <- strptime(total$date,"%Y-%m-%dT%H:%M:%OS")
total$date <- as.Date(total$date)
total$date <- as.factor(total$date)
totalLocked <- total %>% filter(sesType=="LSES") %>% group_by(date) %>% summarise(locked=n())
totalUnlocked <- total %>% filter(sesType=="USES") %>% group_by(date) %>% summarise(unlocked=n())
totalOverall <- total %>% filter(sesType=="LSES"|sesType=="USES") %>% group_by(date) %>% summarise(Overall=n())
View(totalLocked)
View(totalUnlocked)
View(totalOverall)
mean(totalLocked$locked)
mean(totalUnlocked$unlocked)
mean(totalOverall$Overall)
####################################
